### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by nsipplswezey** [SuspiciousPi/SuspiciousPi#77]
Hi SuspiciousPi,

I was able to fork, clone, npm install, bower install, mongod your repo.

But when it came to gulp, I got the following error

``` bash
Nicolass-MacBook-Air:SuspiciousPi nsipplsw$ gulp
[16:33:37] Using gulpfile ~/SuspiciousPi/gulpfile.js
[16:33:37] Starting 'build'...
[16:33:37] Starting 'clean'...
[16:33:37] Starting 'watch'...
[16:33:38] Finished 'watch' after 27 ms
[16:33:38] Starting 'run'...
[16:33:38] Finished 'clean' after 61 ms
[16:33:38] Starting 'compile'...
20 Feb 16:33:38 - [nodemon] v1.3.7
20 Feb 16:33:38 - [nodemon] to restart at any time, enter `rs`
20 Feb 16:33:38 - [nodemon] watching: *.*
20 Feb 16:33:38 - [nodemon] starting `node server.js`
Node app is running at localhost:5000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/nsipplsw/SuspiciousPi/node_modules/react/package.json'

```

Is this a known issue? I saw this post which seemed to provide some guidance.
https://github.com/Banno/grunt-coffeeify/issues/6

Looking forward to getting up and running and contributing to this spectacular project.

Warmly,
Nick

**Comment by cannoneyed** [comment]
Hmm..... are you on mac or pc? this error looks a lot like too many files
are open. Not sure, have you tried gulping the project with no other
processes running?

**Comment by cannoneyed** [comment]
Also what node are you using? (node -v)

**Comment by nsipplswezey** [comment]
Mac. Probably too many files open. Or node version.

Regardless.
Updated node. Reinstalled npm modules. Rebooted.
Up and running. So fly.

![screenshot 2015-02-21 09 52 51](https://cloud.githubusercontent.com/assets/7946707/6315190/ea1e8a0a-b9ae-11e4-94d9-234af9026c9c.png)
